all: default

default:
	gcc -Wall -Werror dirCopy.c userCommands.c handleUser.c repCheck.c source.c -o mcp
clear:
	rm -rf D:\temp\VCrepository
test:
	gcc -Wall -Werror dirCopy.c userCommands.c handleUser.c repCheck.c test.c -o test